name: talkjs
description: TalkJS wrap for dart
version: 0.0.7+1
homepage: https://github.com/leftyio/talkjs
authors: 
  - Kevin Segaud <kevin.segaud@gmail.com>
  - Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  js: ^0.6.1
  dart_browser_loader: ^0.0.4

dev_dependencies:
  test: ^1.3.0
  pedantic: ^1.8.0
