name: talkjs
description: TalkJS wrap for dart
version: 0.0.7
homepage: https://lefty.io
author: Kevin Segaud <kevin.segaud@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  js: ^0.6.1
  dart_browser_loader: ^0.0.4

dev_dependencies:
  test: ^1.3.0
